# Generated by Django 5.1.3 on 2024-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstr_modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_id', models.CharField(max_length=50)),
                ('models_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
