# Generated by Django 5.1.3 on 2024-11-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mstr_modelos',
            new_name='mstr_models',
        ),
    ]
