# Generated by Django 5.1.3 on 2024-11-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_rename_mstr_modelos_mstr_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_name', models.CharField(max_length=100, verbose_name='nombre del pais')),
                ('count_iso3', models.CharField(max_length=100, verbose_name='')),
                ('count_iso2', models.CharField(max_length=100, verbose_name='')),
                ('count_phone_code', models.CharField(max_length=20, verbose_name='codigo de telefono del pais')),
                ('count_concurrencia', models.CharField(max_length=50, verbose_name='codigo de telefono del pais')),
                ('count_tld', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='departaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depar_cod', models.CharField(max_length=20, verbose_name='codigo alfamumerico del departamento')),
                ('depar_descr', models.CharField(max_length=200, verbose_name='Descripcion del departamento')),
            ],
        ),
        migrations.CreateModel(
            name='mstr_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catal_cod', models.CharField(max_length=20, verbose_name='codigo  alfanumerico')),
                ('catal_descr', models.CharField(verbose_name='Descripcion del catalago')),
            ],
        ),
        migrations.CreateModel(
            name='mstr_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_cod', models.CharField(max_length=50, verbose_name='codigo color alfanuemrico')),
                ('color_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mstr_sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_cod', models.CharField(max_length=20, verbose_name='Cdigo de la talla')),
                ('size_desc', models.CharField(verbose_name='Descripcion de la talla')),
            ],
        ),
        migrations.CreateModel(
            name='mstr_subcatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatal_cod', models.CharField(verbose_name='El codigo alfanumerico de catalago')),
                ('subcatal_descr', models.CharField(verbose_name='descrpcion de catalago')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produ_cod', models.CharField(max_length=20, verbose_name='codigo del producto')),
                ('sales_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('sale_datatime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states_name', models.CharField(max_length=100, verbose_name='nombre de la ciudad')),
                ('state_id', models.CharField(max_length=100, verbose_name='nombre de la ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_cod', models.CharField(max_length=30, verbose_name='codido deposito')),
                ('ware_descr', models.CharField(max_length=30, verbose_name='descripcion del deposito')),
            ],
        ),
        migrations.AlterField(
            model_name='mstr_models',
            name='models_id',
            field=models.CharField(max_length=50, verbose_name='clave primaria de la tabla color alfanumerico'),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=50)),
                ('produc_id', models.CharField(max_length=100, verbose_name='codigo del producto')),
                ('sales_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('repos_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('picki_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('order_datetime', models.DateTimeField()),
                ('order_status', models.BooleanField()),
                ('sales_user', models.CharField(max_length=30, verbose_name='nombre del usaurio')),
                ('wh1_user', models.CharField(max_length=30)),
                ('pick_user', models.CharField(max_length=30, verbose_name='nombre del usaurio')),
                ('orde_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.sales')),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='nombre de la ciudad')),
                ('states_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.states')),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppl_tax_name', models.CharField(max_length=100, verbose_name='')),
                ('suppl_short_name', models.CharField(max_length=100, verbose_name='nombre corto')),
                ('suppl_address', models.CharField(max_length=200, verbose_name='direccion proveedor')),
                ('suppl_nr_identif', models.CharField(max_length=200, verbose_name='rif proveedor')),
                ('count_id', models.IntegerField()),
                ('suppl_contact', models.CharField(max_length=100, verbose_name='')),
                ('suppl_email', models.EmailField(max_length=200, verbose_name='correo electronico')),
                ('suppl_phone', models.CharField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.cities')),
                ('states_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.states')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produ_id', models.IntegerField(verbose_name='id del producto de tipo  varchar')),
                ('produ_cod', models.CharField(max_length=50, verbose_name='codigo del producto')),
                ('produc_qr', models.CharField(max_length=50, verbose_name='codigo para generar el codigo QR')),
                ('produ_title', models.IntegerField(max_length=200, verbose_name='titulo  del producto')),
                ('produ_descrip_gral', models.CharField(max_length=200, verbose_name='Descripcion general del prodcuto')),
                ('gender', models.CharField(max_length=100)),
                ('produ_regis_date', models.DateField()),
                ('produ_active', models.BooleanField(default=True)),
                ('cata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.mstr_catalog')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.mstr_color')),
                ('depa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.departaments')),
                ('models_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.mstr_models')),
                ('subcatal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.mstr_subcatalog')),
                ('suppl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locat_code', models.CharField(max_length=30)),
                ('locat_descr', models.CharField(max_length=100, verbose_name='descripcion location')),
                ('wareh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.products')),
                ('wareh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.warehouse')),
                ('locat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.warehouse_location')),
            ],
        ),
    ]
