# Generated by Django 5.1.3 on 2024-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0003_countries_departaments_mstr_catalog_mstr_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='produ_title',
            field=models.CharField(max_length=200, verbose_name='titulo  del producto'),
        ),
    ]
