# Generated by Django 5.1.3 on 2024-11-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0004_alter_products_produ_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_sizes',
            name='size_cod',
            field=models.CharField(max_length=20, verbose_name='Codigo de la talla'),
        ),
        migrations.AlterField(
            model_name='states',
            name='state_id',
            field=models.CharField(max_length=100, verbose_name='id de la ciudad'),
        ),
    ]
