# Generated by Django 5.1.3 on 2024-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0005_alter_mstr_sizes_size_cod_alter_states_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='states_name',
            field=models.CharField(max_length=100, verbose_name='nombre del estado'),
        ),
    ]
