# Generated by Django 5.1.3 on 2024-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0006_alter_states_states_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='count_concurrencia',
            field=models.CharField(max_length=50, verbose_name='count_concurrencia'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='count_iso2',
            field=models.CharField(max_length=100, verbose_name='count_iso2'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='count_iso3',
            field=models.CharField(max_length=100, verbose_name='count_iso3'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='count_tld',
            field=models.CharField(max_length=100, verbose_name='count_tld'),
        ),
    ]
