# Generated by Django 5.1.3 on 2024-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0007_alter_countries_count_concurrencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_models',
            name='models_id',
            field=models.CharField(max_length=50, verbose_name='models_id'),
        ),
    ]
