# Generated by Django 4.2.16 on 2024-11-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0009_cities_countr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='countr_id',
        ),
        migrations.AddField(
            model_name='states',
            name='countr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_inventory.countries'),
        ),
    ]
